import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/provider";
import { SidebarClient } from "@/components/SidebarClient";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`antialiased`}>
          <Toaster position="top-center" reverseOrder={false} />
          <div className="md:flex">
            <SidebarClient />
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
